[package]
name = "rust_playground"
version = "0.1.0"
authors = ["Sean Klein <seanmarionklein@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.7"
